Add task
JuliaZharova/Lecture-10-Zharova pull request #1
Opened 2021-12-04 18:28 UTC by JuliaZharova

2021-12-22 20:51 UTC, ltana requested changes

2021-12-22 20:51 UTC, ltana commented on Lecture-10/src/com/company/Calc.java
> +public class Calc<T extends Number> {
use three different types, not one

2021-12-22 20:51 UTC, ltana commented on Lecture-10/src/com/company/Calc.java
> +    public <T extends Number> double sum (T number1, T number2, T number3) {
use only one sum method which accepts as arguments three different types, not one

2021-12-23 20:45 UTC, JuliaZharova commented on Lecture-10/src/com/company/Calc.java
> +public class Calc<T extends Number> {
fixed

2021-12-23 20:45 UTC, JuliaZharova commented on Lecture-10/src/com/company/Calc.java
> +    public <T extends Number> double sum (T number1, T number2, T number3) {
fixed

2022-01-11 19:53 UTC, ltana requested changes

2022-01-11 19:53 UTC, ltana commented on Lecture-10/src/com/company/Calc.java
> +    public <T extends Number> double sum (T number1, T number2, T number3) {
types are still the same 'T', please use different ones

2022-01-11 21:58 UTC, JuliaZharova commented on Lecture-10/src/com/company/Calc.java
> +    public <T extends Number> double sum (T number1, T number2, T number3) {
fixed

2022-01-20 16:58 UTC, ltana approved these changes
can be merged

2022-01-20 17:21 UTC, merged